### ISSUE TITLE
Will the bakeneko 65 pcb fit ? 

### ISSUE THREAD

**Issue by ttran134** [dayofdoom/savage65-case#1]
As the title stated, Bakeneko 65 is gasket mount and I wonder if I can substitute the savage 65 pcb with it

**Comment by dayofdoom** [comment]
I think it will fit, however the Bakeneko65 PCB uses a daughterboard for the USB-C connection. This case was not designed with that in mind but if you're a motivated keeb hacker, I think you can make it work!

**Comment by ttran134** [comment]
Ahh ok, there is another option which is the KBD 67mkII / 67lite, what are your thoughts on those!

**Comment by dayofdoom** [comment]
So I believe both of those will fit. The Savage65 case is compatible with some other PCBs. Check the product page on CannonKeys. Those additional PCBs will work in this case, because they'll work in the official case. :)

I think many others will too but I have only tested with the Savage65.
